Feature/month value object
NoxOrg/Nox.Types pull request #41
Opened 2023-06-21 14:54 UTC by msadikkoseaupa

2023-06-21 16:37 UTC, rochar requested changes
looks good, just  comments
thks

2023-06-21 16:37 UTC, rochar commented on src/Nox.Types.EntityFramework/MonthConverter.cs
Can we move this class to a subFolder called ./Types/Month? keeping the namespace, and having the same folder struct in Nox.Types,NoxTypes.EntityFramework, and Nox.Types.Tests?

We are working on setting this conventions, maybe you can start following what will be propose, thks a lot

2023-06-21 16:37 UTC, rochar commented on tests/Nox.Types.Tests/NoxMonthTests.cs
Can we move this class to a subFolder called ./Types/Month? keeping the namespace, and having the same folder struct in Nox.Types,NoxTypes.EntityFramework, and Nox.Types.Tests?

And rename the class to MonthTests

We are working on setting this conventions, maybe you can start following what will be propose, thks a lot

2023-06-21 21:37 UTC, msadikkoseaupa commented on src/Nox.Types.EntityFramework/MonthConverter.cs
folder structure was updated as desired

2023-06-21 21:38 UTC, msadikkoseaupa commented on tests/Nox.Types.Tests/NoxMonthTests.cs
folder structure was updated as desired

2023-06-22 06:43 UTC, rochar approved these changes

2023-06-22 08:09 UTC, merged