Implemented Distance type
NoxOrg/Nox.Types pull request #42
Opened 2023-06-21 15:16 UTC by dejobratic

- Created a Distance value object with QuantityValue as underlying type.
- Distance can be created with kilometers and miles as units from a numeric value or two LatLong objects that represent the origin and destination. In the latter case the distance is calculated using the Haversine formula http://www.movable-type.co.uk/scripts/latlong.html.
- ToString method prints the value and symbol for unit.

2023-06-21 16:21 UTC, rochar requested changes
Looks good, just left a few suggestion
Thks

2023-06-21 16:21 UTC, rochar commented on src/Nox.Types.EntityFramework/DistanceConverter.cs
Can we move this class to a subFolder called ./Types/Distance? keeping the namespace, and having the same folder struct in Nox.Types,NoxTypes.EntityFramework, and Nox.Types.Tests?

2023-06-21 16:21 UTC, rochar commented on src/Nox.Types.EntityFramework/DistanceConverter.cs
> +    public DistanceToKilometerConverter() : base(area => (double)area.ToKilometers(), d => Distance.FromKilometers(d)) { }
area variable should be called distance instead?

2023-06-21 16:21 UTC, rochar commented on src/Nox.Types.EntityFramework/DistanceConverter.cs
> +    public DistanceToMilesConverter() : base(area => (double)area.ToMiles(), d => Distance.FromMiles(d)) { }
a suggestion, call d distanceValue for example . So its easier to read?

2023-06-21 16:21 UTC, rochar commented on tests/Nox.Types.Tests/NoxDistanceTests.cs
Can we move this class to a subFolder called ./Types/Distance?
And rename the class to be DistanceTests
We are working on setting this conventions, maybe you can start following what will be propose, thks a lot

2023-06-22 06:21 UTC, dejobratic commented on tests/Nox.Types.Tests/NoxDistanceTests.cs
Thamks for the suggetions. All test classes and EF converters have been renamed and moved to dedicated subfolder (.Types/<type-name>).

2023-06-22 06:29 UTC, rochar approved these changes, later dismissed

2023-06-22 06:35 UTC, rochar commented
@dejobratic on the commit message you can relate to your issue, adding to the description #<issuenumber>

On the issue you can also select your branch or PR:
![image](https://github.com/NoxOrg/Nox.Types/assets/8514193/d48d31e2-eb62-4195-8ae8-6603c314e5ae)

2023-06-22 11:01 UTC, jan-schutte approved these changes
Nicely done @dejobratic

2023-06-22 11:02 UTC, merged