Percentagem implementation
NoxOrg/Nox.Types pull request #66
Opened 2023-06-28 11:35 UTC by denisvieira-dev

2023-06-30 16:00 UTC, rochar requested changes

2023-06-30 16:00 UTC, rochar commented on src/Nox.Types/Types/Percentage/Percentage.cs
> +    public override string ToString()
he ToString must be culture independent, see the Lenght and the Lenght Tests on ToString and also our Readme.md
Thks

2023-06-30 16:00 UTC, rochar commented on src/Nox.Types/Types/Percentage/Percentage.cs
maybe I missing something,

I'm not seeing the Constructor and the From creation with Validation?

2023-06-30 16:00 UTC, rochar commented on src/Nox.Types.EntityFramework/Types/Percentage/PercentageConverter.cs
we need to add this converter and type to the EntityFramework Tests

2023-07-04 07:27 UTC, rochar approved these changes
Looks good

2023-07-04 12:13 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-07-04 12:13 UTC, merged